spring.application.name=SecurityApplication
spring.datasource.url=jdbc:mysql://localhost:3306/securityapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.formate_sql=true
#security configs
#spring.security.user.name=siddharath
#spring.security.user.password=pass
#spring.security.user.role[]={}
jwt.secretKey=ad8emkjmkt55pdmskn12kemo4ldjiklbhyres@njskgringios77lsb

deploy.env = development

